using System.Collections.Generic;

namespace PokeChat.ML;

public static class SeedTrainingData
{
    public static readonly IReadOnlyList<(string Input, string Category)> Examples = new List<(string, string)>
    {
        ("hello", "greeting"),
        ("hi", "greeting"),
        ("hey there", "greeting"),
        ("how are you", "greeting"),
        ("good morning", "greeting"),
        ("good afternoon", "greeting"),
        ("good evening", "greeting"),
        ("howdy", "greeting"),
        ("whats up", "greeting"),
        ("yo", "greeting"),
        ("my name is bob", "name_intro"),
        ("i am alice", "name_intro"),
        ("i'm charlie", "name_intro"),
        ("call me dave", "name_intro"),
        ("you can call me eve", "name_intro"),
        ("they call me frank", "name_intro"),
        ("my name's grace", "name_intro"),
        ("i am known as heidi", "name_intro"),
        ("i like pizza", "preference_statement"),
        ("i love cats", "preference_statement"),
        ("i enjoy hiking", "preference_statement"),
        ("i adore chocolate", "preference_statement"),
        ("i am fond of jazz", "preference_statement"),
        ("i prefer tea over coffee", "preference_statement"),
        ("i really like reading", "preference_statement"),
        ("i am crazy about dogs", "preference_statement"),
        ("i hate spiders", "dislike_statement"),
        ("i dislike rain", "dislike_statement"),
        ("i can't stand traffic", "dislike_statement"),
        ("i loathe cold weather", "dislike_statement"),
        ("i detest waiting in line", "dislike_statement"),
        ("i'm not a fan of horror movies", "dislike_statement"),
        ("i despise lies", "dislike_statement"),
        ("i can't tolerate rudeness", "dislike_statement"),
        ("i have a dog", "possession_statement"),
        ("i own a car", "possession_statement"),
        ("i have two cats", "possession_statement"),
        ("i've got a bicycle", "possession_statement"),
        ("i possess a guitar", "possession_statement"),
        ("i have a brother", "possession_statement"),
        ("i own a house", "possession_statement"),
        ("i have a collection of stamps", "possession_statement"),
        ("i think exercise is important", "belief_statement"),
        ("i believe in hard work", "belief_statement"),
        ("i feel that education matters", "belief_statement"),
        ("in my opinion honesty is best", "belief_statement"),
        ("i consider family to be important", "belief_statement"),
        ("i reckon kindness goes a long way", "belief_statement"),
        ("i suppose patience is a virtue", "belief_statement"),
        ("i am convinced that practice helps", "belief_statement"),
        ("i am tall", "personal_attribute"),
        ("i am a teacher", "personal_attribute"),
        ("i am twenty five years old", "personal_attribute"),
        ("i am from london", "personal_attribute"),
        ("i am a vegetarian", "personal_attribute"),
        ("i am left handed", "personal_attribute"),
        ("i am an engineer", "personal_attribute"),
        ("i am quite shy", "personal_attribute"),
        ("the sky is blue", "general_fact"),
        ("water is wet", "general_fact"),
        ("sugar is sweet", "general_fact"),
        ("fire is hot", "general_fact"),
        ("ice is cold", "general_fact"),
        ("the sun rises in the east", "general_fact"),
        ("grass is green", "general_fact"),
        ("Paris is the capital of France", "general_fact"),
        ("what is 2 plus 2", "math_query"),
        ("calculate 5 times 3", "math_query"),
        ("what is 10 minus 7", "math_query"),
        ("compute 12 divided by 4", "math_query"),
        ("how much is 8 plus 6", "math_query"),
        ("what is 15 percent of 200", "math_query"),
        ("solve 3 plus 4", "math_query"),
        ("what does 9 times 9 equal", "math_query"),
        ("define apple", "dictionary_query"),
        ("what does serendipity mean", "dictionary_query"),
        ("define computer", "dictionary_query"),
        ("meaning of life", "dictionary_query"),
        ("what is the definition of love", "dictionary_query"),
        ("define perseverance", "dictionary_query"),
        ("what does ephemeral mean", "dictionary_query"),
        ("definition of courage", "dictionary_query"),
        ("synonym for happy", "thesaurus_query"),
        ("what is another word for big", "thesaurus_query"),
        ("antonym of hot", "thesaurus_query"),
        ("opposite of fast", "thesaurus_query"),
        ("similar word for beautiful", "thesaurus_query"),
        ("synonym of strong", "thesaurus_query"),
        ("another word for smart", "thesaurus_query"),
        ("what is the opposite of light", "thesaurus_query"),
        ("tell me a story", "story_request"),
        ("make up a story", "story_request"),
        ("tell me a tale", "story_request"),
        ("i want a story", "story_request"),
        ("can you tell me a story", "story_request"),
        ("weave me a story", "story_request"),
        ("tell me an adventure", "story_request"),
        ("create a story for me", "story_request"),
        ("write a poem", "poetry_request"),
        ("write a haiku", "poetry_request"),
        ("compose a limerick", "poetry_request"),
        ("write me a poem", "poetry_request"),
        ("can you write poetry", "poetry_request"),
        ("compose some verses", "poetry_request"),
        ("write a sonnet", "poetry_request"),
        ("make a poem about nature", "poetry_request"),
        ("tell me a joke", "joke_request"),
        ("make me laugh", "joke_request"),
        ("crack a joke", "joke_request"),
        ("do you know any jokes", "joke_request"),
        ("tell me something funny", "joke_request"),
        ("say something funny", "joke_request"),
        ("got any jokes", "joke_request"),
        ("tell me a funny joke", "joke_request"),
        ("i have a riddle for you", "riddle_start"),
        ("let's do a riddle", "riddle_start"),
        ("ask me a riddle", "riddle_start"),
        ("give me a riddle", "riddle_start"),
        ("i want to solve a riddle", "riddle_start"),
        ("riddle me this", "riddle_start"),
        ("do you know any riddles", "riddle_start"),
        ("tell me a riddle", "riddle_start"),
        ("let's play a game", "game_start"),
        ("i want to play a game", "game_start"),
        ("play something with me", "game_start"),
        ("let's do a word game", "game_start"),
        ("can we play a game", "game_start"),
        ("let's play mad libs", "game_start"),
        ("let's play hangman", "hangman_start"),
        ("play hangman with me", "hangman_start"),
        ("i want to play hangman", "hangman_start"),
        ("start a hangman game", "hangman_start"),
        ("let's do hangman", "hangman_start"),
        ("play a game of hangman", "hangman_start"),
        ("you should say hello", "correction_pattern"),
        ("say hi instead", "correction_pattern"),
        ("when i say hi you should say hello", "correction_pattern"),
        ("try saying goodbye instead", "correction_pattern"),
        ("you should respond with okay", "correction_pattern"),
        ("say thanks when i thank you", "correction_pattern"),
        ("when i ask how you are say fine", "correction_pattern"),
        ("goodbye", "farewell"),
        ("see you later", "farewell"),
        ("i have to go", "farewell"),
        ("talk to you later", "farewell"),
        ("catch you later", "farewell"),
        ("see you soon", "farewell"),
        ("farewell", "farewell"),
        ("i'm leaving now", "farewell"),
        ("let's start fresh", "reset_request"),
        ("reset everything", "reset_request"),
        ("start over", "reset_request"),
        ("wipe all my data", "reset_request"),
        ("clear everything", "reset_request"),
        ("forget everything", "reset_request"),
        ("start afresh", "reset_request"),
        ("clean slate please", "reset_request"),
        ("you are great", "compliment_request"),
        ("you are amazing", "compliment_request"),
        ("you are so smart", "compliment_request"),
        ("you are wonderful", "compliment_request"),
        ("i like you", "compliment_request"),
        ("you are the best", "compliment_request"),
        ("you are awesome", "compliment_request"),
        ("tell me about myself", "about_me_query"),
        ("what do you know about me", "about_me_query"),
        ("what have i told you", "about_me_query"),
        ("what do you remember about me", "about_me_query"),
        ("tell me what you know", "about_me_query"),
        ("what facts do you have about me", "about_me_query"),
        ("what do i like", "about_me_query"),
        ("what are my interests", "about_me_query"),
        ("show me my stats", "stats_query"),
        ("how many facts do you know", "stats_query"),
        ("how many conversations have we had", "stats_query"),
        ("what are your statistics", "stats_query"),
        ("give me some stats", "stats_query"),
        ("how much do you know", "stats_query"),
        ("what are my conversation stats", "stats_query"),
        ("tell me the statistics", "stats_query"),
        ("what is the weather", "weather_query"),
        ("what's the weather like", "weather_query"),
        ("how's the weather", "weather_query"),
        ("is it going to rain today", "weather_query"),
        ("is it going to rain", "weather_query"),
        ("do i need an umbrella", "weather_query"),
        ("what's the temperature outside", "weather_query"),
        ("how hot is it today", "weather_query"),
        ("how cold is it", "weather_query"),
        ("will it snow today", "weather_query"),
        ("is it cold today", "weather_query"),
        ("is it hot today", "weather_query"),
        ("weather in london", "weather_query"),
        ("weather in paris", "weather_query"),
        ("tell me the forecast", "weather_query"),
        ("what's the forecast for tomorrow", "weather_query"),
        ("is it sunny today", "weather_query"),
        ("how's the weather looking", "weather_query"),
        ("should i bring a jacket", "weather_query"),
        ("what's the humidity like", "weather_query"),
        ("is it going to be warm today", "weather_query"),
        ("what's the weather in tokyo", "weather_query"),
        ("yes", "yes_no_affirmation"),
        ("yeah", "yes_no_affirmation"),
        ("sure", "yes_no_affirmation"),
        ("ok", "yes_no_affirmation"),
        ("okay", "yes_no_affirmation"),
        ("no", "yes_no_affirmation"),
        ("nope", "yes_no_affirmation"),
        ("correct", "yes_no_affirmation"),
        ("who are you", "question_about_bot"),
        ("what are you", "question_about_bot"),
        ("are you a robot", "question_about_bot"),
        ("can you think", "question_about_bot"),
        ("do you have feelings", "question_about_bot"),
        ("are you sentient", "question_about_bot"),
        ("what is this", "question_about_bot"),
        ("are you alive", "question_about_bot"),
        ("why is the sky blue", "complex_question"),
        ("what is the meaning of life", "complex_question"),
        ("how do airplanes fly", "complex_question"),
        ("what is artificial intelligence", "complex_question"),
        ("how does the internet work", "complex_question"),
        ("why do we dream", "complex_question"),
        ("what causes climate change", "complex_question"),
        ("how do vaccines work", "complex_question"),
        ("why do people get old", "complex_question"),
        ("how does photosynthesis work", "complex_question"),
        ("xylophone quantum paradigm", "unknown"),
        ("giraffe nebula traction", "unknown"),
        ("moonstone alchemy cryptic", "unknown"),
        ("thunder fractal entropy", "unknown"),
        ("crystal prism oscillation", "unknown"),
        ("velvet horizon migration", "unknown"),
        ("amber cosine lattice", "unknown"),
        ("zephyr tungsten mosaic", "unknown"),
        ("the flobberwocky mimsied the borogoves", "unknown"),
        ("quasar blinker fluid calibration", "unknown"),
    };
}
